### ISSUE TITLE
Pre-defined name of the operational points.

### ISSUE THREAD

**Issue by francois-keith** [stack-of-tasks/sot-dynamic#2]
Hello all,

In the script humanoid.py, some operational points are predefined

<pre>
    OperationalPoints = ['left-wrist', 'right-wrist',
                         'left-ankle', 'right-ankle',
                         'gaze']
</pre>

Using dashes in the name of the signals prevents calling them directly in python:

<pre>
robot.dynamics.left-wrist
</pre>

will return an error, rather than display the value of the homogeneous matrix.
I regret the loss of this functionality. Wouldn't it be better to use underscores instead?

Regards

François

**Comment by florent-lamiraux** [comment]
Hello François,

For each of these names, a member is created in the robot class according to the following pattern:
left-wrist -> leftWrist
right-ankle -> rightAnkle
gaze -> gaze.

Florent
