### ISSUE TITLE
leftHand / rightHand frames and grippers

### ISSUE THREAD

**Issue by francois-keith** [stack-of-tasks/sot-dynamic#5]
Hello

I have a question regarding the additional frames created in the method initializeRobot (in humanoid_robots.py)
https://github.com/stack-of-tasks/sot-dynamic/blob/master/src/dynamic_graph/sot/dynamics/humanoid_robot.py#L298-L313
The two frames created, leftHand and rightHand, correspond to the "geometric parameters of hand"
For the robot hrp2, these frames are the same than the r_gripper and l_gripper frames in the urdf files.
(cf http://www.ros.org/reps/rep-0120.html#l-gripper-and-r-gripper)
Is this a coincidence or are those two frames (LeftHand / l_gripper) identical?

Is it possible to replace (or create an alias in the latter case) the frames "Left/Right Hand" by the frames "Left/RightGripper" (in order to be closer to the REP120 specifications)?

**Comment by francois-keith** [comment]
My mistake, the two transformations are different in the case of the hrp2, hence the question is different:

I'd like to make the gripper frames accessible in the python interface.
Should those frames replace those of the hands, or simply be added aside?

**Comment by florent-lamiraux** [comment]
On 12/11/2013 04:01 PM, François Keith wrote:

> My mistake, the two transformations are different in the case of the
> hrp2, hence the question is different:
> 
> I'd like to make the gripper frames accessible in the python interface.
> Should those frames replace those of the hands, or simply be added aside?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stack-of-tasks/sot-dynamic/issues/5#issuecomment-30326841.

Dear François,

Hands and grippers are the same. Do not create additional frames for 
grippers. If the word "hand" is an issue, create a reference to the 
frames instead.

Florent
